### PR TITLE
Assignment 5 - PC2 - Car Class

### PR DESCRIPTION
**Pull request by srtinkey**
Create a class named Car and use it in a program.

The Car class has 3 fields:  yearModel, make, and speed. It has a
constructor and accessor methods and accelerate (increase speed by 5)
and brake (decrease speed by 5) methods.

### CODE REVIEW

**Comment by ninjapanzer** [comment]
Looking good :+1:

**Comment by srtinkey** [comment]
Some how I've uploaded a whole new set of files, Assignment5 #4 (not sure how I got this name either). These files are not my final submission. Please see Assignment5 #4.

**Comment by srtinkey** [comment]
I would delete these if I could.

**Comment by ninjapanzer** [comment]
You can always close the pr sort out your files create a new branch and open another pr

**Comment by steve-plas** [comment]
@srtinkey Very nice code!

**Pull request closed without merging**
